#! /bin/bash

#dir=`yad --width=400 --title="Путь к локальному git-репозиторию" --entry`

XTERM="lxterminal  --working-directory='$1' -e"
GDIFF="sh -c 'git diff | yad --text-info --lang=diff --image=gtk3-demo --title=Сравнение_файлов --width=950 --height=650 --button=Выход:1'"

yad --form --width=250 --image=org.gnome.gitg --text="Выберите команду git клиента:" --title="Графическая оболочка для GIT" \
--field="Получить":fbtn "$XTERM 'git pull; bash'" \
--field="Загрузить":fbtn "$XTERM 'git push; bash'" \
--field="Добав. и фиксировать":fbtn "$XTERM 'git add --all; GIT_EDITOR=leafpad git commit'" \
--field="Добавить":fbtn "$XTERM 'git add --all'" \
--field="Фиксировать":fbtn "$XTERM 'GIT_EDITOR=leafpad git commit; sleep 3'" \
--field="Создать":fbtn "$XTERM 'git init; sleep 1'" \
--field="Статус":fbtn "$XTERM 'git status; bash'" \
--field="Терминал":fbtn "$XTERM 'bash'" \
--field="gitg":fbtn "gitg" \
--field="Сравнить рабочий каталог":fbtn "$GDIFF" \
--button=Выход:1
