#! /bin/bash

#dir=`yad --width=400 --title="Путь к локальному git-репозиторию" --entry`

XTERM="lxterminal  --working-directory='$1' -e"

yad --form --width=250 --text="Выберите команду git клиента:" --title="Графическая оболочка для GIT" \
--field="Получить":fbtn "$XTERM 'git pull; bash'" \
--field="Загрузить":fbtn "$XTERM 'git push; bash'" \
--field="Добавить":fbtn "$XTERM 'git add --all; bash'" \
--field="Фиксировать":fbtn "$XTERM 'GIT_EDITOR=leafpad git commit; bash'" \
--field="Создать":fbtn "$XTERM 'git init; bash'" \
--field="Статус":fbtn "$XTERM 'git status; bash'" \
--field="Терминал":fbtn "$XTERM 'bash'" \
--field="gitg":fbtn "gitg" \
--field="Сравнить рабочий каталог":fbtn "$XTERM 'git diff; bash'" \
--button=Выход:1
