#! /bin/bash

# Copyright (C) 2019-2020  Максим Кутный <gtk3@inbox.ru>
uri=`yad --width=400 --title="Путь к удаленному git-репозиторию" --entry`
XTERM="lxterminal  --working-directory='$1' -e"
$XTERM "git clone $uri; bash"
